name: MoneyMiner
version: 1.0
main: com.foxsrv.moneyminer.Main
api-version: 1.21
depend: [Vault]
commands:
  miner:
    description: Comando principal do MoneyMiner
    usage: /miner <reload>
    aliases: [mminer]
